#set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets reset_N]
set_property PACKAGE_PIN A8         [get_ports {reset_n}]
set_property IOSTANDARD LVCMOS18    [get_ports {reset_n}]

set_property PACKAGE_PIN F7         [get_ports {DATA[0]}]
set_property PACKAGE_PIN F8         [get_ports {DATA[1]}]
set_property PACKAGE_PIN D6         [get_ports {DATA[2]}]
set_property PACKAGE_PIN D7         [get_ports {DATA[3]}]
set_property PACKAGE_PIN E8         [get_ports {DATA[4]}]
set_property PACKAGE_PIN G6         [get_ports {DATA[5]}]
set_property PACKAGE_PIN E5         [get_ports {DATA[6]}]
set_property PACKAGE_PIN E6         [get_ports {DATA[7]}]
set_property PACKAGE_PIN F6         [get_ports {EN}]
set_property PACKAGE_PIN G7         [get_ports {RS}]

set_property IOSTANDARD LVCMOS18    [get_ports {DATA[0]}]
set_property IOSTANDARD LVCMOS18    [get_ports {DATA[1]}]
set_property IOSTANDARD LVCMOS18    [get_ports {DATA[2]}]
set_property IOSTANDARD LVCMOS18    [get_ports {DATA[3]}]
set_property IOSTANDARD LVCMOS18    [get_ports {DATA[4]}]
set_property IOSTANDARD LVCMOS18    [get_ports {DATA[5]}]
set_property IOSTANDARD LVCMOS18    [get_ports {DATA[6]}]
set_property IOSTANDARD LVCMOS18    [get_ports {DATA[7]}]
set_property IOSTANDARD LVCMOS18    [get_ports {EN}]
set_property IOSTANDARD LVCMOS18    [get_ports {RS}]


